### ISSUE TITLE
Channel, direct message or private group not found

### ISSUE THREAD

**Issue by luisvae** [kfei/slack-cleaner#13]
When trying to erase all messages from a user we get this result:

Channel, direct message or private group not found

We used: 

slack-cleaner --token [TOKEN] --message --channel gossip  --user [USER] --perform

Any ideas?

**Comment by hukevinxiaochen** [comment]
Shot in the dark here, but is `gossip` one of your channels? If not, you might want to change it to a channel that you actually have. If you want to delete messages from all the public channels, you might try not using the channel option at all and go with:

`slack-cleaner --token <TOKEN> --message --user <USER> --perform`

**Comment by Nokius** [comment]
@hukevinxiaochen this returns a `slack-cleaner: error: one of the arguments --channel --direct --group --mpdirect is required` :'( but it would be a nice option
