### ISSUE TITLE
Question about Token

### ISSUE THREAD

**Issue by daylerees** [kfei/slack-cleaner#18]
Hi there, what type of token should I use for the app? Under custom integrations I see Bots, but that doesn't seem to work. Is there another way of getting a token?

**Comment by lindsaymarkward** [comment]
@daylerees - You should be able to generate a token here: https://api.slack.com/docs/oauth-test-tokens
See docs: https://get.slack.help/hc/en-us/articles/215770388-Creating-and-regenerating-API-tokens

**Comment by mraaroncruz** [comment]
Just in case they remove the redirect, the above link is now redirecting here: https://api.slack.com/custom-integrations/legacy-tokens.
You need to log in with one or more slack teams before you can generate anything.

**Comment by daylerees** [comment]
Woop, this got lost to time. Thanks for answering, though! I'll close the issue. :)
