### ISSUE TITLE
Change rate arg type from int to float

### ISSUE THREAD

**Issue by arimus** [kfei/slack-cleaner#38]
Changing to float will allow 0.25 / 0.5 / etc. to be specified, which can help prevent the rate limiting errors, but also still perform more operations.

p.s. Thanks for the tool. Very helpful!

**Comment by jaketoolson** [comment]
https://github.com/kfei/slack-cleaner/pull/37

**Comment by arimus** [comment]
Dunno how I missed that ticket when looking for dupes, but I did. Closing.
