### ISSUE TITLE
How to get slack to allow authorization?

### ISSUE THREAD

**Issue by ocheret** [kfei/slack-cleaner#60]
New to Slack apps. Created an app on slack to get a token. Turned on assorted permissions but when I run the slack-cleaner I ultimately get a stack trace and 'slacker.Error: invalid_auth'.

It would be helpful if the readme had a short description of what to do on the Slack side of config.

**Comment by sgratzl** [comment]
see https://github.com/sgratzl/slack-cleaner#tokens and https://github.com/sgratzl/slack-cleaner#minimal-slack-permission-scopes-required

**Comment by ocheret** [comment]
Thanks! I was not using a legacy token before.

**Comment by shanness** [comment]
Thanks for this app!  Life saver!  Would be good to put this in the current readme, it's missing from that, and I had to find it in the closed issues.

**Comment by sgratzl** [comment]
> Thanks for this app! Life saver! Would be good to put this in the current readme, it's missing from that, and I had to find it in the closed issues.

well there are already pull requests for that but the author if this repo never merged them. Thus I created my fork:  https://github.com/sgratzl/slack-cleaner#tokens
