### ISSUE TITLE
Cleaning with --bot argument is deleting posts by users

### ISSUE THREAD

**Issue by NJ0** [kfei/slack-cleaner#7]
Thanks for this very useful program, it was an extremely pleasing experience watching all of slackbots old reminder messages disappear!

I've encountered an issue trying to clean up bot posts in public channels, the syntax:
`slack-cleaner --token TOKEN --channel test --message --bot --perform`
cleans posts by users as well as bots (almost as if I hadn't used the --bot argument). 

For example, in an empty test channel I posted two "asdasd" messages and ran the cleaner using the aforementioned synatx and got the following result:
![22-03-2016 1-46-12 pm](https://cloud.githubusercontent.com/assets/17996957/13940808/fdabff2c-f034-11e5-9f21-5ec90f324154.png)

Both my messages get deleted and I'm pretty sure I'm not a bot. Any ideas as to what I'm doing wrong?

**Comment by kfei** [comment]
Should be fixed in 0.2.0. Many thanks for reporting! :smile:

**Comment by NJ0** [comment]
I can confirm the fix works in 0.2.0. Thank you for your hard work!
