### ISSUE TITLE
wait time to delete message

### ISSUE THREAD

**Issue by grambharos** [kfei/slack-cleaner#76]
I want to execute the command for executing messages for bots. But i get timeouts.
Message:
Failed to delete (429 Client Error: Too Many Requests for url: https://slack.com/api/chat.delete?token=tokenname)->

Is it possible to add a timeout in the command. like seconds and minutes before deleting a message(bot/app)?

**Comment by sgratzl** [comment]
it is already implemented,

```
--rate=<delay-in-seconds> to reduce the API call rate (which by default is unlimited).
```

**Comment by grambharos** [comment]
Thank you sgratzl
