### ISSUE TITLE
need time delay between each delete call

### ISSUE THREAD

**Issue by yuvarajancitspl** [kfei/slack-cleaner#82]
https://github.com/kfei/slack-cleaner/blob/11686f8b2d9d0f3e6a48ccf8c1fa3daf7a0af62e/slack_cleaner/cli.py#L141

need to add sleep of 1.5 seconds between each delete call, so we can avoid rate limit error.
As delete API call belongs to [tier3](https://api.slack.com/docs/rate-limits#tier_t3), it allows only 50+ API call per minute.

**Comment by ventz** [comment]
Thanks! This fixed the problem.

Added a ~2~ 1 second delay, and the yellow "Failed to delete ->" went away.

**Comment by peechyfloof** [comment]
Just use the parameter "--rate [seconds]"

**Comment by ventz** [comment]
Thanks. Saw this too as I started poking at the code.

**Comment by peechyfloof** [comment]
Same on my side ;D
But when youŕe done, feel free to close the issue!

**Comment by yuvarajancitspl** [comment]
as @MKHSKY mentioned, time.sleep functionality is already available as parameter "--rate [secod]", so am closing this issue.
