### ISSUE TITLE
Syntax error when using the docker image

### ISSUE THREAD

**Issue by pdMa2s** [kfei/slack-cleaner#84]
This was my command:
`$ docker run --rm kfei/slack-cleaner slack-cleaner --help`
And this was the resulting output: 
`import: unable to open X server ' @ error/import.c/ImportImageCommand/364.
import: unable to open X server ' @ error/import.c/ImportImageCommand/364.
/usr/local/bin/slack-cleaner: line 7: from: command not found
/usr/local/bin/slack-cleaner: slack-cleaner: line 10: syntax error near unexpected token ('
/usr/local/bin/slack-cleaner: slack-cleaner: line 10:     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])'`

**Comment by sgratzl** [comment]
can you try the docker image of my fork: `docker pull sgratzl/slack-cleaner`

**Comment by pdMa2s** [comment]
Hi @sgratzl , thank you for your reply.
`$ docker run --rm sgratzl/slack-cleaner slack-cleaner --help` seems to generate a similar error:

_/usr/local/bin/slack-cleaner: line 3: import: command not found
/usr/local/bin/slack-cleaner: line 4: import: command not found
/usr/local/bin/slack-cleaner: line 6: from: command not found
/usr/local/bin/slack-cleaner: slack-cleaner: line 9: syntax error near unexpected token ('
/usr/local/bin/slack-cleaner: slack-cleaner: line 9:     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])'_

If it helps, I am using Docker 19.03.1-ce.

**Comment by sgratzl** [comment]
I was just checking it, can you please try: 

```bash
docker run --rm sgratzl/slack-cleaner -c "slack-cleaner --help"
```

or
```bash
docker run --rm -it sgratzl/slack-cleaner
slack-cleaner --help
```

**Comment by pdMa2s** [comment]
Both commands yielded the correct output. Thank you
