### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by renshuki** [kfei/slack-cleaner#9]
Hi,
You did a great job with this library. Thank you.
A nice feature would be to use argument --no-log to skip logging ;)

**Comment by kfei** [comment]
Sounds good. Thanks for the suggestion. :smile: I'll add this flag when I have some free time. As always, pull requests are welcome!

**Comment by renshuki** [comment]
I thought it was better to use --log to create a log file than --no-log to skip it.
If you prefer to implement --no-log instead I can create another pull request.
Let me know ;)

**Comment by kfei** [comment]
@renshuki Awesome! Many thanks for your fast PR. And the `--log` design looks pretty good to me. :smile:

**Comment by renshuki** [comment]
@kfei Thank you for the merge! =) I close the issue. I'll let you know if I have other improvement ideas.

**Comment by kfei** [comment]
Sweet!
